apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/dns-manager
  - ../../base/observability
  - windns-known-hosts.example.yml
images:
  - name: ghcr.io/chernyakia/consul-dns-failover-dns-controller
    newTag: latest
