apiVersion: v1
kind: Secret
metadata:
  name: consul-dns-manager-token
  namespace: consul
type: Opaque
stringData:
  token: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-manager-selectel-secrets
  namespace: consul
type: Opaque
stringData:
  SEL_ACCOUNT_ID: REPLACE_ME
  SEL_SERVICE_USER: REPLACE_ME
  SEL_SERVICE_PASS: REPLACE_ME
  SEL_PROJECT_NAME: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-manager-windns-secrets
  namespace: consul
type: Opaque
stringData:
  WIN_SSH_HOST: dns01.internal.example.com
  WIN_SSH_USER: REPLACE_ME
  WIN_SSH_PASSWORD: REPLACE_ME
