apiVersion: v1
kind: Secret
metadata:
  name: dns-manager-windns-secrets
  namespace: <FILL_THIS_FIELD>
data:
  WIN_SSH_HOST: <FILL_THIS_FIELD>
  WIN_SSH_USER: <FILL_THIS_FIELD>
  WIN_SSH_PASSWORD: <FILL_THIS_FIELD>
