apiVersion: v1
kind: Secret
metadata:
  name: dns-manager-selectel-secrets
  namespace: <FILL_THIS_FIELD>
data:
  SEL_ACCOUNT_ID: <FILL_THIS_FIELD>
  SEL_SERVICE_USER: <FILL_THIS_FIELD>
  SEL_SERVICE_PASS: <FILL_THIS_FIELD>
  SEL_PROJECT_NAME: <FILL_THIS_FIELD>
